### ISSUE TITLE
Opening ProgramsFragment may cause NPE

### ISSUE THREAD

**Issue by alexmozzhakov** [alexmozzhakov/doHabit#7]
```
FATAL EXCEPTION: main
Process: com.doapps.habit, PID: 5915
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v4.app.Fragment.setNextAnim(int)' on a null object reference
    at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:765)
    at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2579)
    at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2366)
    at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2321)
    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2228)
    at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:699)
    at android.os.Handler.handleCallback(Handler.java:746)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5443) at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
```

**Comment by alexmozzhakov** [comment]
```
FATAL EXCEPTION: main
Process: com.doapps.habit, PID: 7696
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.doapps.habit/com.doapps.habits.activity.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.firebase.database.DataSnapshot com.google.firebase.database.DataSnapshot.child(java.lang.String)' on a null object reference
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2426)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
    at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4098)
    at android.app.ActivityThread.-wrap15(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1360)
    at android.os.Handler.dispatchMessage(Handler.java:102) at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.firebase.database.DataSnapshot com.google.firebase.database.DataSnapshot.child(java.lang.String)' on a null object reference
    at com.doapps.habits.fragments.ProgramFragment.onCreateView(ProgramFragment.java:60)
    at android.support.v4.app.Fragment.performCreateView(Fragment.java:2337)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1418)
    at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1739)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1808)
    at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3216)
    at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3170)
    at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:2352)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1441)
    at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1739)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1808)
    at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3216)
    at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3170)
    at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:192)
    at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:552)
    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1260)
    at android.app.Activity.performStart(Activity.java:6261)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2389)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490) 
    at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4098) 
    at android.app.ActivityThread.-wrap15(ActivityThread.java) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1360) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:148) 
    at android.app.ActivityThread.main(ActivityThread.java:5443) at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) 
```

**Comment by deepaksime** [comment]
whats the solution..

**Comment by alexmozzhakov** [comment]
@deepaksime I've changed logic a bit, now DataSnapshot isn't being passed as an object but used a reference to the database instead.
